# Configuração do cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# node 1
- role: control-plane
  # mapeando a porta 30000 do node para a localhost:8080
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
# node 2
# - role: worker

# Para criar esse cluster com essa configuração use:
# $ kind create cluste --config=cluster-config.yaml

### OBS:
# não está funcionando. tente usar o port-foward no pod