apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    resources:
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
