apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias-pod
  labels:
    app: portal-noticias-pod
spec:
  containers:
    - name: portal-noticias
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap