apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello-pod
spec:
  containers:
  - name: hello-pod
    image: localhost:5000/api-go:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3333

# ----
---

apiVersion: v1
kind: Service
metadata:
  name: svc-hello
spec:
  selector:
    app: hello-pod
  ports:
  - port: 8080
    targetPort: 3333

