
# definir deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-conversor
  template:
    metadata:
      labels:
        app: web-conversor
    spec:
      containers:
      - name: conversor-container
        image: jp0user0docker/conversao-temperatura:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
