version: '3'

services:
  #serviço 1
  nginx:
    image: nginx:latest
    # local:container
    ports:
      - "8080:80"
    # local:container
    volumes:
      - .:/user/share/nginx/html/
  #seviço 2
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROT_PASSWORD=<>
      - MYSQL_DATABASE=teste
    volumes:
      - ./data:/var/lib/mysql/